// import { Geist, Geist_Mono } from "next/font/google";
import { Exo_2 } from 'next/font/google'
import "./globals.css"; // Ensure this file exists in the same directory
import { UIProvider } from "@/heroui/HeroUIProvider";
import '.././public/fonts/fonts.css';
//Analytics from vercel
import { Analytics } from "@vercel/analytics/next"

const exo2 = Exo_2({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-exo2', // CSS variable name
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon links */}
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png" />
        <link rel="manifest" href="/assets/favicon/site.webmanifest" />
        <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
      </head>

      <body className={`${exo2.variable} antialiased`}>
        <UIProvider>
          {children}
        </UIProvider>
      </body>
      
    </html>
  );
}
